# Generated by Django 4.1.7 on 2023-04-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="link",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="source_description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="sourcedata",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="sourcedata",
            name="link",
            field=models.TextField(default=""),
        ),
    ]
