# Generated by Django 4.1.7 on 2023-04-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_image_link_alter_product_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="link",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="source_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="sourcedata",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="sourcedata",
            name="link",
            field=models.TextField(null=True),
        ),
    ]
