# Generated by Django 4.1.7 on 2023-02-26 18:59

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="embedding_vector",
            field=djongo.models.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_path",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
