# Generated by Django 4.1.7 on 2023-04-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_image_link_alter_product_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Thời gian tạo", null=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Thời gian cập nhật", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Thời gian tạo", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Thời gian cập nhật", null=True
            ),
        ),
        migrations.AlterField(
            model_name="producttest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Thời gian tạo", null=True
            ),
        ),
        migrations.AlterField(
            model_name="producttest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Thời gian cập nhật", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sourcedata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Thời gian tạo", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sourcedata",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Thời gian cập nhật", null=True
            ),
        ),
    ]
