# Generated by Django 4.1.7 on 2023-02-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_product_image_product_embedding_vector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
