# Generated by Django 4.1.7 on 2023-04-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_image_created_at_alter_image_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.TextField(null=True),
        ),
    ]
