# Generated by Django 4.1.7 on 2023-03-03 21:22

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_product_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default={}, max_length=100, null=True)),
                ("image_url", models.CharField(default={}, max_length=250, null=True)),
                ("image_path", models.CharField(default={}, max_length=100, null=True)),
                (
                    "embedding_vector",
                    djongo.models.fields.JSONField(default={}, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Thời gian cập nhật"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Thời gian tạo"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
