# Generated by Django 4.1.7 on 2023-04-04 18:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttest",
            name="embedding_vector",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), null=True, size=None
                ),
                null=True,
                size=None,
            ),
        ),
    ]
