# Generated by Django 4.1.7 on 2023-03-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_product_sourcedata_alter_producttest_image_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default="2023-03-04T09:16:24.414Z",
                help_text="Thời gian tạo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Thời gian cập nhật"),
        ),
        migrations.AddField(
            model_name="sourcedata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default="2023-03-04T09:16:24.414Z",
                help_text="Thời gian tạo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourcedata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Thời gian cập nhật"),
        ),
    ]
