# Generated by Django 4.1.7 on 2023-04-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_producttest_embedding_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttest",
            name="embedding_vector",
            field=models.TextField(null=True),
        ),
    ]
