# Generated by Django 4.1.7 on 2023-03-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_image_created_at_image_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(default="", max_length=250, null=True),
        ),
    ]
