# Generated by Django 4.1.7 on 2023-03-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_product_name_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="link",
            field=models.CharField(default="", max_length=250, null=True),
        ),
    ]
