# Generated by Django 4.1.7 on 2023-04-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="embedding_vector",
            field=models.TextField(null=True),
        ),
    ]
