# Generated by Django 4.1.7 on 2023-03-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_describe_sourcedata_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcedata",
            name="min_page",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
