# Generated by Django 4.1.7 on 2023-03-07 17:01

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_sourcedata_min_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedata",
            name="key_words",
            field=djongo.models.fields.JSONField(default={}, null=True),
        ),
    ]
