# Generated by Django 4.1.7 on 2023-03-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_product_key_words"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="key_words",
        ),
    ]
