# Generated by Django 4.1.7 on 2023-03-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_image_embedding_vector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourcedata",
            name="key_words",
        ),
        migrations.RemoveField(
            model_name="sourcedata",
            name="max_page",
        ),
        migrations.RemoveField(
            model_name="sourcedata",
            name="min_page",
        ),
        migrations.RemoveField(
            model_name="sourcedata",
            name="multi_page",
        ),
    ]
