# Generated by Django 4.1.7 on 2023-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_remove_product_key_words_product_source_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedata",
            name="crawled",
            field=models.BooleanField(default=False),
        ),
    ]
