# Generated by Django 4.1.7 on 2023-03-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_sourcedata_crawled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourcedata",
            name="crawled",
        ),
    ]
