# Generated by Django 4.1.7 on 2023-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_remove_sourcedata_crawled"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedata",
            name="crawled",
            field=models.BooleanField(default=False),
        ),
    ]
