# Generated by Django 4.1.7 on 2023-03-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_sourcedata_crawled"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="crawled",
            field=models.BooleanField(default=False),
        ),
    ]
