# Generated by Django 4.1.7 on 2023-04-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_remove_sourcedata_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_raw",
            field=models.CharField(default="", max_length=250),
        ),
    ]
