# Generated by Django 4.1.7 on 2023-04-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_category_name_raw"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rembg",
            field=models.BooleanField(default=False),
        ),
    ]
