# Generated by Django 4.1.7 on 2023-04-13 11:57

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_product_rembg"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttest",
            name="embedding_vector_rembg",
            field=djongo.models.fields.JSONField(default={}, null=True),
        ),
    ]
