# Generated by Django 4.1.7 on 2023-04-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_image_embedding_vector_temp"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=250, null=True)),
                ("running", models.BooleanField(default=False)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Thời gian cập nhật"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Thời gian tạo"),
                ),
            ],
        ),
    ]
